# Generated by Django 6.0.1 on 2026-02-02 12:21
from django.contrib.postgres.operations import TrigramExtension
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='job_posting_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
